export const projects = [
  {
    id: 1,
    name: "Project A",
    description: "This is the first example project.",
    lead: "John Doe",
    technologiesUsed: ["HTML5", "CSS3", "JavaScript"],
    images: [
      "https://www.svgrepo.com/show/452228/html-5.svg",
      "https://www.svgrepo.com/show/452185/css-3.svg",
      "https://www.svgrepo.com/show/353925/javascript.svg",
    ],
  },
  {
    id: 2,
    name: "Project B",
    description: "A second project to illustrate the array of objects.",
    lead: "Jane Smith",
    technologiesUsed: ["React", "Node.js", "Express"],
    images: [
      "https://www.svgrepo.com/show/452092/react.svg",
      "https://www.svgrepo.com/show/354119/nodejs-icon.svg",
      "https://www.svgrepo.com/show/353724/express.svg",
    ],
  },
  {
    id: 3,
    name: "Project C",
    description: "Another interesting project.",
    lead: "Mike Johnson",
    technologiesUsed: ["Python", "Django", "PostgreSQL"],
    images: [
      "https://www.svgrepo.com/show/452091/python.svg",
      "https://www.svgrepo.com/show/373554/django.svg",
      "https://www.svgrepo.com/show/354200/postgresql.svg",
    ],
  },
  {
    id: 4,
    name: "Project D",
    description: "The last project in this example.",
    lead: "Alice Brown",
    technologiesUsed: ["Java", "Spring Boot", "MySQL"],
    images: [
      "https://www.svgrepo.com/show/452234/java.svg",
      "https://www.svgrepo.com/show/376350/spring.svg",
      "https://www.svgrepo.com/show/373848/mysql.svg",
    ],
  },
  {
    id: 5,
    name: "Project E",
    description: "An additional project with repeated technologies.",
    lead: "Eva White",
    technologiesUsed: ["React", "Node.js", "Express", "JavaScript"],
    images: [
      "https://www.svgrepo.com/show/452092/react.svg",
      "https://www.svgrepo.com/show/354119/nodejs-icon.svg",
      "https://www.svgrepo.com/show/353724/express.svg",
      "https://www.svgrepo.com/show/353925/javascript.svg",
    ],
  },
  {
    id: 6,
    name: "Project F",
    description: "A new project with unique challenges.",
    startDate: "2023-11-05",
    lead: "Grace Johnson",
    technologiesUsed: ["Vue.js", "Node.js", "MongoDB"],
    images: [
      "https://www.svgrepo.com/show/493625/vue-vuejs-javascript-js-framework.svg",
      "https://www.svgrepo.com/show/354119/nodejs-icon.svg",
      "https://www.svgrepo.com/show/373845/mongo.svg",
    ],
  },
  {
    id: 7,
    name: "Project G",
    description: "Exploring cutting-edge technologies.",
    startDate: "2023-12-20",
    lead: "Michael Brown",
    technologiesUsed: ["TensorFlow", "Keras", "Python"],
    images: [
      "https://www.svgrepo.com/show/473805/tensorflow.svg",
      "https://www.svgrepo.com/show/341962/keras.svg",
      "https://www.svgrepo.com/show/452091/python.svg",
    ],
  },
  {
    id: 8,
    name: "Project H",
    description: "A project aimed at sustainability.",
    startDate: "2024-01-15",
    lead: "Sophia Adams",
    technologiesUsed: ["React", "Node.js", "Express", "JavaScript"],
    images: [
      "https://www.svgrepo.com/show/452092/react.svg",
      "https://www.svgrepo.com/show/354119/nodejs-icon.svg",
      "https://www.svgrepo.com/show/353724/express.svg",
      "https://www.svgrepo.com/show/353925/javascript.svg",
    ],
  },
  {
    id: 9,
    name: "Project I",
    description: "Bringing AI to everyday life.",
    startDate: "2024-02-28",
    lead: "Ethan Wilson",
    technologiesUsed: ["Python", "PyTorch", "Django"],
    images: [
      "https://www.svgrepo.com/show/452091/python.svg",
      "https://www.svgrepo.com/show/354240/pytorch.svg",
      "https://www.svgrepo.com/show/373554/django.svg",
    ],
  },
  {
    id: 10,
    name: "Project J",
    description: "A creative project in the arts.",
    startDate: "2024-04-10",
    lead: "Olivia Martinez",
    technologiesUsed: ["JavaScript", "HTML5", "CSS3"],
    images: [
      "https://www.svgrepo.com/show/353925/javascript.svg",
      "https://www.svgrepo.com/show/452228/html-5.svg",
      "https://www.svgrepo.com/show/452185/css-3.svg",
    ],
  },
];
